name: Django Web Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  web-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.13
    
    - name: Install UV
      run: |
        python -m pip install --upgrade pip
        pip install uv
    
    - name: Run Django migrations (check)
      run: |
        uv run python manage.py check --deploy
    
    - name: Run web tests  
      run: |
        uv run pytest web_tests/
    
    - name: Test Django server startup
      run: |
        timeout 10s uv run python manage.py runserver --noreload || true
        echo "Django server startup test completed"
    
    - name: Run Django system checks
      run: |
        uv run python manage.py check